In [7]:
class Employee:
    numberOfEmployees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.numberOfEmployees+=1


def averagesalary(employee):
    total = sum(e.salary for e in employee)
    average = total / len(employee)
    return average

class Full_time_Employee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self,name, family, salary, department)

print("Employee 1: ")
employee_1 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Employee 2: ")
employee_2 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Full Time Employee 1: ")
employee_3 = Full_time_Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("")
print("Number of employees: ",Employee.numberOfEmployees)
list_of_Employees = [employee_1, employee_2]
avgsalary = averagesalary(list_of_Employees)
print("Avgerage salary  :", avgsalary)


Employee 1: 
Enter name: Mohith
Family Members: 4
Employee Salary: 5000
Employee Department: IT
Employee 2: 
Enter name: Jay
Family Members: 4
Employee Salary: 10000
Employee Department: Electric
Full Time Employee 1: 
Enter name: Deva
Family Members: 4
Employee Salary: 100000
Employee Department: Police

Number of employees:  3
Avgerage salary  : 7500.0


In [5]:
import numpy

temp_vector = numpy.random.uniform(1, 20, 20)
print(temp_vector)
print("")
print("")
New_array = temp_vector.reshape(4, 5)
print("")
print("")
print(New_array)
New_array[numpy.arange(4), numpy.argmax(New_array, axis=1)] = 0
print("")
print("")
print(New_array)

[19.23639968 11.78917247  8.07295761 14.21125584  7.1408186   2.66753786
 11.79674164 15.60501677 11.38617195 11.09363231  5.74513624  1.87293712
  6.24125912 10.4757783   6.4176995   2.21999525  2.55973975  6.20468367
  2.93293574  3.13470877]




[[19.23639968 11.78917247  8.07295761 14.21125584  7.1408186 ]
 [ 2.66753786 11.79674164 15.60501677 11.38617195 11.09363231]
 [ 5.74513624  1.87293712  6.24125912 10.4757783   6.4176995 ]
 [ 2.21999525  2.55973975  6.20468367  2.93293574  3.13470877]]


[[ 0.         11.78917247  8.07295761 14.21125584  7.1408186 ]
 [ 2.66753786 11.79674164  0.         11.38617195 11.09363231]
 [ 5.74513624  1.87293712  6.24125912  0.          6.4176995 ]
 [ 2.21999525  2.55973975  0.          2.93293574  3.13470877]]
